version: '3'
services:
    php:
        build:
            context: ./docker/php
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./shop:/var/www/shop/:cached
            - ${COMPOSER_CACHE_DIR:-~/.composer/cache}:/root/.composer/cache

    mysql:
        image: 'mysql:5.5'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            TZ: 'Europe/Berlin'
        volumes:
            - ./docker/mysql/lib:/var/lib/mysql
            - ./docker/mysql/etc:/etc/mysql/conf.d
