# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    base.helper:
        # as no class is configured, the parent service MUST be abstract
        abstract: true
        arguments: [ '@doctrine.orm.entity_manager' ]
        #arguments: [ '@doctrine.orm.entity_manager' , '@service_container' ]

    product.helper:
        class: AppBundle\Helper\ProductHelper
        parent: base.helper


    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
